language: go

go:
 - 1.x
 - 1.14.x
 - 1.13.x
 - 1.12.x

install:
 - go get -t -v ./...

script:
 - go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
